### ISSUE TITLE
Docs, examples, and articles

### ISSUE THREAD

**Issue by doowb** [node-toolkit/docs#1]
References to docs, examples, and articles to sort through to add to the docs. I'm still updating this.

### Docs and examples from issue comments

 - [ ] [build cycle docs and "use with gulp" example](https://github.com/assemble/assemble-workshop/issues/3)
 - [ ] [assemble features](https://github.com/assemble/assemble/issues/720#issuecomment-164110162)
 - [ ] [modify dest example](https://github.com/assemble/assemble-permalinks/issues/2#issuecomment-165867508)
 - [ ] [load collection and push to stream](https://github.com/assemble/assemble-permalinks/issues/2#issuecomment-167597124)
 - [ ] [assemble tags example](https://github.com/assemble/assemble-tags-collection-example)
 - [ ] [custom data loader example](https://github.com/assemble/assemble/issues/865#issuecomment-222369074)
 - [ ] [onMerge middleware, using with nunjucks examples](https://github.com/assemble/assemble/issues/886#issuecomment-233940456)
 - [ ] [using `{{#withSort}}` to create navigation menus](https://github.com/helpers/handlebars-helpers/issues/200)
 - [ ] [description of data, middleware, pipeline plugins and how it's all used throughout the render cycle to calculate relative paths for use when rendering](https://github.com/assemble/assemble/issues/908#issuecomment-270895439)
 - [ ] [using `{{sortBy}}` as a subexpression in `{{each}}`](https://github.com/assemble/assemble/issues/918#issuecomment-278332595)
 - [ ] [example using `.build` directly without the CLI, using with browser-sync, and handling errors](https://github.com/assemble/assemble/issues/919#issuecomment-280667090)
 - [ ] [setting `layoutDelims` for custom body tags](https://github.com/assemble/assemble/issues/909#issuecomment-291582341)
 - [ ] [page data context, working with yaml front-matter](https://github.com/assemble/assemble/issues/928#issuecomment-308955519)
 - [ ] [async-helpers usage and what arguments are passed to helpers](https://github.com/doowb/async-helpers/issues/13#issuecomment-298337732)

### Articles and blog posts

 - http://atelierbram.github.io/blog/assembling/
 - http://www.andismith.com/
 - http://qliksite.io/articles/goodbye-wordpress/
 - http://webercoder.com/technology/2015/05/04/building-an-assembleio-blog.html

**Comment by jonschlinkert** [comment]
http://webercoder.com/technology/2015/05/04/building-an-assembleio-blog.html

**Comment by mootari** [comment]
I'd also add [Get the collection a view belongs to in a middleware](https://github.com/assemble/assemble/issues/836#issuecomment-188371762).

**Comment by mootari** [comment]
[Renaming files and views](https://github.com/assemble/assemble/issues/858#issuecomment-220173631)
